---
# Vagrant hostname and IP configuration.
vagrant_hostname: backdrop.dev
vagrant_ip: 192.168.88.111
vagrant_user: vagrant

# A list of synced folders, with the keys 'local_path', 'destination', 'id', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares).
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_from_makefile is 'true'.
  - local_path: ~/Sites/backdropvm
    destination: /var/www
    id: backdropdev
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 2

# Set this to false if you are using a different site deployment strategy and
# would like to configure 'vagrant_synced_folders' and 'apache_vhosts' manually.
build_from_makefile: false
drush_makefile_path: /vagrant/backdrop.make.yml

# Settings for building a Backdrop site from a makefile (if 'build_from_makefile'
# is 'true').
backdrop_major_version: 1 
backdrop_core_path: "/var/www/backdrop"
backdrop_domain: "backdrop.dev"
backdrop_site_name: "Backdrop Dev Site"
backdrop_install_profile: standard
backdrop_enable_modules: [ 'devel' ]
backdrop_account_name: admin
backdrop_account_pass: admin
backdrop_mysql_user: backdrop
backdrop_mysql_password: backdrop

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
apache_vhosts:
  - {servername: "{{ backdrop_domain }}", documentroot: "{{ backdrop_core_path }}"}
  - {servername: "local.xhprof.com", documentroot: "/usr/share/php/xhprof_html"}

# MySQL Databases and users. If build_from_makefile is true, first database will
# be used for the makefile-built site.
mysql_databases:
  - name: backdrop
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: backdrop
    host: "%"
    password: backdrop
    priv: "backdrop.*:ALL"

# Comment out any extra utilities you don't want to install.
installed_extras:
  - mailhog
  - memcached
  - phpmyadmin
  # - solr
  - xdebug
  - xhprof

# You can configure almost anything else on the server in the rest of this file.
mysql_root_password: root
drush_version: master
drush_keep_updated: yes

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "8025"
  - "8080"
  - "8443"
  - "8983"

# PHP Configuration. Currently-supported versions: 5.5, 5.6, 7.0 (experimental).
php_version: "5.5"
php_memory_limit: "192M"
php_display_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"

# Disable main XDebug components unless needed.
php_xdebug_coverage_enable: 0
php_xdebug_default_enable: 0

solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"
